baseURL = "https://tochange.fr"
languageCode = "fr-FR"
title = "Cursus POEC DevOps"

ignorefiles = [ "vagrant-ansible-elk/.*" ]

# Modifiez le thème pour qu'il soit utilisé par défaut à chaque génération de site.
theme = "hugo-theme-learn"

# Pour la fonctionnalité de recherche
[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
editURL = "https://github.com/e-lie/hugo_cursus_janvier2020"
globalTitle = "POEC DevOps 2021"

[params.reveal_hugo]
custom_theme = "reveal-hugo/themes/robot-lung.css"

# [menu.shortcuts]

[markup.goldmark.renderer]
unsafe = true

# [menu.shortcuts]
