filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true
    filebeat.modules:
    - module: container
    - module: docker
    - module: system

filebeat.autodiscover:
  providers:
    - type: docker
#       templates:
#         # - condition.contains:
#         #     docker.container.image: nginx
#         - config:
#             - type: log
#               paths:
#                 - "/var/lib/docker/containers/${data.docker.container.id}/*.log"
     # - type: docker
      hints.enabled: true
      # json.expand_keys: true
      # json.add_error_key: true
      # hints.default_config:
      #   type: container
        # co.elastic.logs/json.message_key: message
      # json.message_key: message  
      # templates:
      #   - config:
      #       # - type: json
      #       - type: docker
      #         containers.ids: "*"
      #         containers.path: /var/lib/docker/containers
      #         json.keys_under_root: true
      #         json.add_error_key: true
      # co.elastic.logs/json.expand_keys: true
      # co.elastic.logs/json.add_error_key: true
      # co.elastic.logs/json.message_key: message
      # co.elastic.logs/json.message_key: log

# filebeat.inputs:
#   - type: docker
#     containers.ids: "*"
#     containers.paths: /var/lib/docker/containers/${data.docker.container.id}/${data.docker.container.id}-json.log
#     json.expand_keys: true
#     json.add_error_key: true
#     json.message_key: message
      # json.message_key: log

  # paths:
  #  - '/var/lib/docker/containers/*/*.log'
  # json.message_key: log
  # json.keys_under_root: true
    # processors:
    #   - add_docker_metadata: ~
      # - decode_json_fields:
      #     fields: ["message"]
          # process_array: false
        # max_depth: 1
        # target: ""
          # overwrite_keys: false
          # add_error_key: true
output.elasticsearch:
  hosts: ["http://es01:9200","http://es02:9200","http://es03:9200"]

# processors:
# - add_cloud_metadata: ~

# output.elasticsearch:
#   hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
#   username: '${ELASTICSEARCH_USERNAME:}'
#   password: '${ELASTICSEARCH_PASSWORD:}'
